cran <- function(correct=T){
  database <- .readRDS(file=url("http://cran.r-project.org/web/packages/packages.rds",encoding="UTF-8"))
  authors <- database[,13]
  pkgs <- database[,1]
  authors <- iconv(authors, from ="UTF-8", to = "UTF-8")
  authors <- gsub(authors,pattern="\n",replacement=" ")
  authors <- gsub("[[:space:]]*<[^>]+@[^>]+>", "", authors)
  names(authors) <- NULL
  authors <- gsub(authors,pattern=" with support and contributions from Pfizer, Inc.",replacement="")
  authors <- gsub(authors,pattern="(with )?(the )?(additional )?(considerable )?(substantial )?contributions?( of code)? (from|by|of) ",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="Original data sets from various sources.",replacement="",ignore.case=T)
  authors <- gsub(authors,pattern="originally ?(written )?(for S-plus )?(by|from)?",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="(for )?(based on )?(S |S-plus )?(C )?original ?(version )?(S )?(S-plus )?(code )?(functions? )?(of|by|from)?",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="(C++)",replacement="",fixed=T)
  authors <- gsub(authors,pattern="(R)",replacement="",fixed=T)
  authors <- gsub(authors,pattern="and with general advice from the R-help listserv community, especially Duncan Murdoch.",replacement=",")
  authors <- gsub(authors,pattern="(with )?(assistance|help|inputs|support|advice) from",replacement=",")
  authors <- gsub(authors,pattern="supported by ",replacement=",")
  authors <- gsub(authors,pattern="(support, descriptions)",replacement="")
  authors <- gsub(authors,pattern="R documentation( and examples )?by",replacement="")
  authors <- gsub(authors,pattern="some documentation and unit tests ported from Allen Day's ``getopt`` package. Based on the optparse Python library by the Python Software Foundation.",replacement="")
  authors <- gsub(authors,pattern="R port and R documentation files by ",replacement="")
  authors <- gsub(authors,pattern="(initial )?R( |-)port( of [[:graph:]]+)?( and [[:graph:]]+)?( by| from)?",replacement=",")
  authors <- gsub(authors,pattern="port to R",replacement=",")
  authors <- gsub(authors,pattern="except some R port of the SFMT algorithm ",replacement=",")
  authors <- gsub(authors,pattern="translated to|ported to",replacement="",ignore.case=T)
  authors <- gsub(authors,pattern="translated to|ported by",replacement="",ignore.case=T)
  authors <- gsub(authors,pattern="porting to R by",replacement="",ignore.case=T)
  authors <- gsub(authors,pattern="R port + extensions by",replacement=",",fixed=T)
  authors <- gsub(authors,pattern="(with )?extensions( and adaptations)?( of )?[[:graph:]]*( by)?",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="Toplevel R functions and much more by ",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="(for all )?[[:graph:]]* (R )?functions?( [[:graph:]]*)?( by)?",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="[[:alpha:]]+.[[:alpha:]]+ by ",replacement=",",fixed=T)
  authors <- gsub(authors,pattern=" as well as code fragments and ideas from the former package 'sound' by Matthias Heymann.",replacement=",")
  authors <- gsub(authors,pattern="transition to Plan 9 codebase by ",replacement=",")
  authors <- gsub(authors,pattern="with code for case-control data contributed by",replacement=",")
  authors <- gsub(authors,pattern="based on code written during 2005 and 2006 by",replacement=",")
  authors <- gsub(authors,pattern=" also based on C-code developed by",replacement="")
  authors <- gsub(authors,pattern="[[:punct:]]s code",replacement=",")
  authors <- gsub(authors,pattern="(Includes )?(partly based on )?(based on the )?(based in part on )?(using )?(with )?(some )?(additional )?(Fortran )?(R )?(source )?(interface )?(C([[:punct:]]{1,2})? ?)?([[:graph:]]* )?code( for [[:graph:]]*)?( and/or documentation)?( adapted| contributed| developed| written)?( by| from| of)?",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="R interface( etc)? by ",replacement=",")
  authors <- gsub(authors,pattern="based on the sources of",replacement=",")
  authors <- gsub(authors,pattern="R implementation by ",replacement=",")
  authors <- gsub(authors,pattern="multiplicative updates (Lee and Sung 2001) and alternating least squares algorithm; Lars Kai Hansen's nnmf_als Matlab implementation; ",replacement="",fixed=T)
  authors <- gsub(authors,pattern="(for )?(with )?(many )?(various )?suggestions( and contributions)?( by)?",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="modifications( for 7th edition)?( and packaging)?( by)?",replacement=",")
  authors <- gsub(authors,pattern="(revised and)? modified by",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="building on the work of",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="adapted (from )?the work of ",replacement="")
  authors <- gsub(authors,pattern="Adapted to new R releases by ",replacement=",")
  authors <- sub(authors,pattern="(S )?scripts( by)?",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="up to version 2.0, version 2.1 by",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="(this )?(following )?(earlier )?(R )?(S )?(S-plus )?versions?( [[:digit:]].[[:digit:]]{1,2})?( by)?",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="(following )?earlier (work|version|develope?ments) by",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="(adapted )?(changes )?(and )?packaged( for R)?( and enhanced)?( by)?",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern=". Only some additional menus were adapted for the QCA package by",replacement=",",fixed=T)
  authors <- gsub(authors,pattern="from package R.utils by",replacement=",",fixed=T)
  authors <- gsub(authors,pattern="Unless otherwise noted, the contents of this package were written by ",replacement="")
  authors <- gsub(authors,pattern="are Copyright (c) 2007 by Random Technologies LLC <http://random-technologies-llc.com>, and are provided under the terms of the GNU General Public License, , or later. -- The files 'ieee2ibm.c' and 'ibm2ieee.c' were extracted from BRL-CAD, file /brlcad/src/libbu/htond.c written by Michael John Muuss, Copyright (c) 2004-2007 United States Government as represented by the U.S. Army Research Laboratory, and is utilized and redistributed under the terms of the GNU Lesser General Public License, ,. -- The files 'AFirst.lib.s', 'all.is.numeric.R', 'importConvertDateTime.R', 'in.opererator.R', 'makeNames.R', 'read.xport.R', and 'testDateTime.R' are copied or adapted from the 'Hmisc' package created by Frank E. Harrell, Jr., and are utilized and redistributed under the terms of the GNU General Public License, , or later. -- The creation of this package was partially funded by Metrum Institute <http://metruminstitute.org>.",replacement="",fixed=T)
  authors <- gsub(authors,pattern=" -- The creation of this package was partially funded by Metrum Institute",replacement="")
  authors <- gsub(authors,pattern="simpls.fit (package pls) by ",replacement=",",fixed=T)
  authors <- gsub(authors,pattern=" (colors were taken from RColorBrewer package)",replacement=",",fixed=T)
  authors <- gsub(authors,pattern=", inspired by the estout package for Stata",replacement=",")
  authors <- gsub(authors,pattern=" based on",replacement=",")
  authors <- gsub(authors,pattern="[[:graph:]]* written by ",replacement=",")
  authors <- gsub(authors,pattern=" authored( by)?",replacement=",")
  authors <- gsub(authors,pattern=" and much more by ",replacement=",")
  authors <- gsub(authors,pattern="Compiled by ",replacement=",", ignore.case=T)
  authors <- gsub(authors,pattern="Algorithm by ",replacement=",", ignore.case=T)
  authors <- gsub(authors,pattern="with ideas ",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="R by ",replacement="")
  authors <- gsub(authors,pattern="method by ",replacement=",")
  authors <- gsub(authors,pattern="derived (from )?[[:graph:]]* ?by ",replacement=",")
  authors <- gsub(authors,pattern=" together with",replacement=",")
  authors <- gsub(authors,pattern="and by ",replacement=",")
  authors <- gsub(authors,pattern="partly by ",replacement=",")
  authors <- gsub(authors,pattern="packaging by ",replacement=",")
  authors <- gsub(authors,pattern="Rice University's DSP group",replacement="")
  authors <- gsub(authors,pattern="Information and Communications University",replacement="")
  authors <- gsub(authors,pattern="Universite Paris Dauphine",replacement="")
  authors <- gsub(authors,pattern="(The )?([[:upper:]][[:lower:]]+ State )?University( of [[:upper:]][[:lower:]]+)?",replacement=",")
  authors <- gsub(authors,pattern="Universite (du|de) [[:upper:]][[:lower:]]+( a [[:upper:]][[:lower:]]+)?",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern=",Matlab routines by ",replacement=",")
  authors <- gsub(authors,pattern="Some routines from vegan --",replacement="",ignore.case=T)
  authors <- gsub(authors,pattern="(and )?(many )?(potentially )?others?( users)?( contributors)?",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="and colleagues",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern=",many specialists from around the world",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern=" many authors, notably ",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern=" et. al.",replacement="",fixed=T)
  authors <- gsub(authors,pattern=" et al",replacement="",fixed=T)
  authors <- gsub(authors,pattern=" et al.",replacement="",fixed=T)
  authors <- gsub(authors,pattern="([[:graph:]]* ?by )?(the )?(R|Rmetrics)( development)?(( |-)core)?( team| members)",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="the R community",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="R Hackathon",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="(adopted to )?(recent )?(Fortran )?(and )?(S-PLUS|S\\+) (library )?(by |from )?",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="with embedded ,?(Fortran code )? due to ",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="(based on )?FORTRAN( program [[:graph:]]*)?( by)?",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern=" and the Sobol sequence the ACM transactions).",replacement=",",fixed=T)
  authors <- gsub(authors,pattern="See LICENCE file for details.",replacement=",",fixed=T)
  authors <- gsub(authors,pattern=" see README.",replacement=",")
  authors <- gsub(authors,pattern="Copyright [[:punct:]][[:digit:]]{4}[[:punct:]]",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="See the SOURCE file",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="see COPYRIGHTS file in the sources.",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="see file 'Copyrights'",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern=" Instituto de Estudios Biofuncionales(U.C.M.).",replacement="",fixed=T)
  authors <- gsub(authors,pattern=", National Institutes for Standards and Technology (NIST) http://www.itl.nist.gov/div898/strd/nls/nls_main.shtml ",replacement="",fixed=T)
  authors <- gsub(authors,pattern="Centre of Biomedical Informatics, Institute of Computer Science, Academy of Sciences of the Czech Republic",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern=", Assistant Professor, Department of Statistics and Actuarial Science, University of Waterloo, Waterloo, ON, N2L 3G1, Canada",replacement="")
  authors <- gsub(authors,pattern="Pharmacotherapy Outcomes Research Center, Univs?ertiy of Utah",replacement="")
  authors <- gsub(authors,pattern=", IPS LMU Muenchen",replacement=",")
  authors <- gsub(authors,pattern="IPDS CAU Kiel",replacement=",")
  authors <- gsub(authors,pattern="(UQAM)",replacement="",fixed=T)
  authors <- gsub(authors,pattern="(KU Leuven)",replacement="",fixed=T)
  authors <- gsub(authors,pattern="(NYU.edu)",replacement="",fixed=T)
  authors <- gsub(authors,pattern="Insightful Corp(.|oration)",replacement=",")
  authors <- gsub(authors,pattern="(INRA)",replacement="",fixed=T)
  authors <- gsub(authors,pattern="[[:punct:]]Applied Physics Laboratory",replacement=",")
  authors <- gsub(authors,pattern=" (UMH EcoNum)",replacement="",fixed=T)
  authors <- gsub(authors,pattern=", CSBio lab.",replacement="",fixed=T)
  authors <- gsub(authors,pattern=", and members of the CASTLE group at UPR-Mayaguez, Puerto Rico.",replacement="",fixed=T)
  authors <- gsub(authors,pattern=", U.Washington, Seattle. ",replacement=",",fixed=T)
  authors <- gsub(authors,pattern=" at TU-Wien; since 2003-12: ",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="CSIRO Bioinformatics, ",replacement="",ignore.case=T)
  authors <- gsub(authors,pattern=", Assistant Professor, Department of Statistics and Actuarial Science, ,, Waterloo, ON, N2L 3G1, Canada",replacement="",ignore.case=T)
  authors <- gsub(authors,pattern="Pharmac,apy Outcomes Research Center",replacement="",ignore.case=T)
  authors <- gsub(authors,pattern="Zementis Inc",replacement="",ignore.case=T)
  authors <- gsub(authors,pattern="(UA-Birmingham)",replacement="",fixed=T)
  authors <- gsub(authors,pattern="(UW-Madison)",replacement="",fixed=T)
  authors <- gsub(authors,pattern="(Jackson Laboratory)",replacement="",fixed=T)
  authors <- gsub(authors,pattern=" College of William and Mary, Dept. of Physics, 2009",replacement="",fixed=T)
  authors <- gsub(authors,pattern="Icelandic Met. Office;",replacement="",fixed=T)
  authors <- gsub(authors,pattern="Dept. Mathematics and Statistics,",replacement="",fixed=T)
  authors <- gsub(authors,pattern="the Pacific Climate Impacts Consortium",replacement="")
  authors <- gsub(authors,pattern="<o.granert <at> neurologie.uni-kiel.de>",replacement="")
  authors <- gsub(authors,pattern="(I am|We are) grateful to ",replacement=",")
  authors <- gsub(authors,pattern="Special thanks to ",replacement=",")
  authors <- gsub(authors,pattern=" under the supervision of( Dr.)? ",replacement=",")
  authors <- gsub(authors,pattern="(funded as part of the DEFRA VTRI project 0101).",replacement=",",fixed=T)
  authors <- gsub(authors,pattern=" SAIC-Frederick, Inc. Funded by the Intramural Research Program, of the NIH, National Cancer Institute, Center for Cancer Research under NCI Contract NO1-CO-12400.",replacement=",",fixed=T)
  authors <- gsub(authors,pattern="(duncan@wald.ucdavis.edu)",replacement="",fixed=T)
  authors <- gsub(authors,pattern="[[:lower:]]+.[[:lower:]]+@unige.ch",replacement="")
  authors <- gsub(authors,pattern="[[:lower:]]+.[[:lower:]]+@unine.ch",replacement="")
  authors <- gsub(authors,pattern="@uia.ua.ac.be",replacement="",fixed=T)
  authors <- gsub(authors,pattern="@R-project.org",replacement="",fixed=T)
  authors <- gsub(authors,pattern="[[:lower:]]+@[[:lower:]]+\\.[[:lower:]]{2,3}",replacement=",")
  authors <- gsub(authors,pattern=" for the ,idea of storing candidate models in a list.",replacement=",",fixed=T)
  authors <- gsub(authors,pattern="'Project Pluto'",replacement=",",fixed=T)
  authors <- gsub(authors,pattern="(www.projectpluto.com/calendar)",replacement=",",fixed=T)
  authors <- gsub(authors,pattern="Material from the book's webpage, ",replacement="")
  authors <- gsub(authors,pattern=" with information from [[:punct:]]Measurement System Assessment Via Generalized Inference[[:punct:]] by Michael Hamada and Sam Weerandi",replacement="")
  authors <- gsub(authors,pattern="[[:punct:]]amp;",replacement=",")
  authors <- gsub(authors,pattern="This package is 99%, the Rcmdr ,",replacement=",",fixed=T)
  authors <- gsub(authors,pattern=". zlib from",replacement=",",fixed=T)
  authors <- gsub(authors,pattern="; see, [[:punct:]]{1,2}getHostname.System[[:punct:]]{1,2} , ",replacement=",")
  authors <- gsub(authors,pattern="and from 1999 to Oct 2002 ",replacement=",")
  authors <- gsub(authors,pattern=" (during 2008)",replacement="",fixed=T)
  authors <- gsub(authors,pattern="RSvgDevice by",replacement=",",fixed=T)
  authors <- gsub(authors,pattern="TISEAN authors: ",replacement="")
  authors <- gsub(authors,pattern="(CSDP by ",replacement="",fixed=T)
  authors <- gsub(authors,pattern="(EPRI)",replacement="",fixed=T)
  authors <- gsub(authors,pattern="aspline",replacement="",fixed=T)
  authors <- gsub(authors,pattern=" enhancements( and corrections)? by ",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="from StatLib",replacement=",")
  authors <- gsub(authors,pattern="[[:punct:]]s Moore-Penrose",replacement="")
  authors <- gsub(authors,pattern=" [aut, cre]",replacement="",fixed=T)
  authors <- gsub(authors,pattern=" [ctb]",replacement="",fixed=T)
  authors <- gsub(authors,pattern=" for el.test())",replacement=",",fixed=T)
  authors <- gsub(authors,pattern="(EVIS)",replacement=",",fixed=T)
  authors <- gsub(authors,pattern="Fortunes?",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="; fdGPH(), fdSperio(), etc by ",replacement=",",fixed=T)
  authors <- gsub(authors,pattern="(, and 4.4) ",replacement="",fixed=T)
  authors <- gsub(authors,pattern=" GPC library by",replacement=",")
  authors <- gsub(authors,pattern="(in alphabetical order)",replacement=",",fixed=T)
  authors <- gsub(authors,pattern="alphabetically: ",replacement="")
  authors <- gsub(authors,pattern="qrng",replacement=",",fixed=T)
  authors <- gsub(authors,pattern="and multimin by ",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="hwexact()",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="tests etc: ",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="latentnetHRT",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="packages of `statnet' project",replacement=",",ignore.case=T)
  authors <- gsub(authors,pattern="(F77 , ,); ",replacement=",",fixed=T)
  authors <- gsub(authors,pattern=" Datasets via ",replacement=",",fixed=T)
  authors <- gsub(authors,pattern="lp_solve <http://lpsolve.sourceforge.net/>",replacement="",fixed=T)
  authors <- gsub(authors,pattern="rpart",replacement="",fixed=T)
  authors <- gsub(authors,pattern=" to mvpart by",replacement="",fixed=T)
  authors <- gsub(authors,pattern="(Dunnett, Appl Stats., 1989)",replacement="",fixed=T)
  authors <- gsub(authors,pattern="\\(up to [[:digit:]]{4}\\)",replacement="")
  authors <- gsub(authors,pattern="2007-2009",replacement="")
  authors <- gsub(authors,pattern="(arules)",replacement="",fixed=T)
  authors <- gsub(authors,pattern="(except underlying ,s of (i) the SFMT algorithm from M. Matsumoto and M. Saito, (ii) the Knuth-TAOCP RNG from D. Knuth). ,",replacement="",fixed=T)
  authors <- gsub(authors,pattern="(with part of , modified from bugs.R, http://www.stat.columbia.edu/~gelman/bugsR/, by ",replacement=",",fixed=T)
  authors <- gsub(authors,pattern="cddlib (ver ,",replacement="",fixed=T)
  authors <- gsub(authors,pattern="Portions , and/or corrections were contributed by ",replacement=",")
  authors <- gsub(authors,pattern="goodness of fit by ",replacement=",")
  authors <- gsub(authors,pattern="\\([[:digit:]]{4}\\)",replacement="")
  authors <- gsub(authors,pattern="\\(aka Produnis\\)",replacement="")
  authors <- gsub(authors,pattern="; see,",replacement=",")
  authors <- gsub(authors,pattern="Virgilio G<f3>mez-Rubio",replacement="Virgilio Gomez-Rubio")
  authors <- gsub(authors,pattern="Wavelet-based aCGH",replacement=",")
  authors <- gsub(authors,pattern="downloaded from <http://www.ee.technion.ac.il/people/YoninaEldar/Info/software/HaarSeg.htm>",replacement=",",fixed=T)
  authors <- gsub(authors,pattern="Scientific Software Development - Dr. ",replacement="")
  authors <- gsub(authors,pattern="www.linhi.com",replacement="",fixed=T)
  authors <- gsub(authors,pattern="inverse function",replacement="")
  authors <- gsub(authors,pattern="The Cuba library has",replacement="")
  authors <- gsub(authors,pattern="<http://statwww.epfl.ch/davison/BMA/library.html>",replacement="")
  authors <- gsub(authors,pattern="Financial support for some aspects of this package provided by Metrum Research Group, LLC <http://www.metrumrg.com>.",replacement="")
  authors <- gsub(authors,pattern="in the XGobi distribution. Windows port, this and",replacement="")
  authors <- gsub(authors,pattern="for the ptr_container library",replacement=",")
  authors <- gsub(authors,pattern="for the Boost Test Library. And the authors of , Boost libraries used by the previous two.",replacement=",")
  authors <- gsub(authors,pattern="http://wwwth.mppmu.mpg.de/members/hahn",replacement=",",fixed=T)
  authors <- gsub(authors,pattern="builtin from the following R contributed packages: gmm",replacement=",")
  authors <- gsub(authors,pattern="H2( is)?",replacement=",")
  authors <- gsub(authors,pattern=" gld ",replacement=",")
  authors <- gsub(authors,pattern=" gss ",replacement=",")
  authors <- gsub(authors,pattern="nortest",replacement=",")
  authors <- gsub(authors,pattern="HyperbolicDist",replacement=",")
  authors <- gsub(authors,pattern="sandwich",replacement=",")
  authors <- gsub(authors,pattern="The students of the `Advanced R Programming Course'",replacement=",")
  authors <- gsub(authors,pattern="Portfolio",replacement=",")
  authors <- gsub(authors,pattern="<andy.south[at]cefas.co.uk>,<southandy[at]gmail.com>",replacement=",",fixed=T)
  authors <- gsub(authors,pattern=",poon",replacement=",")
  authors <- gsub(authors,pattern=" on a ",replacement=",")
  authors <- gsub(authors,pattern=" by ",replacement=",")
  authors <- gsub(authors,pattern=" with ",replacement=",")
  authors <- gsub(authors,pattern="(\\<| )from ",replacement=",")
  authors <- gsub(authors,pattern=" for,?",replacement=",")
  authors <- gsub(authors,pattern=" of ",replacement=",")
  authors <- gsub(authors,pattern=" are ",replacement=",")
  authors <- gsub(authors,pattern="various",replacement=",")
  authors <- gsub(authors,pattern=" see ",replacement=",")
  authors <- gsub(authors,pattern="(,| )the(,| )",replacement=",")
  authors <- lapply(authors,.asplit)
  names(authors) <- pkgs
  authors <- lapply(authors,clean1)
  pattern <- c("Joern Schulz Peter Toft Jesper James Jensen Peter Philipsen"
    ,"Hector Corrada Bravo Brian Borchers"
    ,"Enio Jelihovschi Jose Claudio Faria Sergio Oliveira"
    ,"Enio Jelihovschi Jose Claudio Faria Sergio Oliveira"
    ,"Federico Girosi Gary King Jon Bischof"
    ,"Stefano Iacus Gary King Giuseppe Porro"
    ,"J H Maindonald Randall Johnson"
    ,"Derek Young Tatiana Benaglia Didier Chauveau Ryan Elmore Tom Hettmansperger David Hunter Hoben Thomas Fengjuan Xuan"
    ,"Peter Filzmoser Heinrich Fritz Klaudius Kalcher"
    ,"Nicole Kraemer Anne Laure Boulesteix"
    ,"Yaqian Guo Trevor Hastie Robert Tibshirani"
    ,"Adelchi Azzalini B D Ripley"
    ,"Jorge Orestes Cerdeira Pedro Duarte Silva Jorge Cadima Manuel Minhoto"
    ,"Marco Riani Luca Scrucca"
    ,"Brian Ripley Jari Oksanen"
    ,"Vincent Carey Thomas Lumley"
    ,"Laurie Davies Arne Kovac"
    ,"Christopher Jackson Thorsten Ottosen"
    ,"Karsten Tabelow Joerg Polzehl"
    ,"Sebastian Krey Uwe Ligges Olaf Mersmann"
    ,"Patrick Burns Nick Efthymiou"
    ,"Heinrich Fritz Klaudius Kalcher"
    ,"Stefano Iacus Gary King Giuseppe Porro"
    ,"Marek Walesiak Andrzej Dudek")
  replacement <- list(c("Joern Schulz", "Peter Toft", "Jesper James Jensen", "Peter Philipsen")
    ,c("Hector Corrada","Bravo Brian Borchers")
    ,c("Enio Jelihovschi", "Jose Claudio Faria", "Sergio Oliveira")
    ,c("Enio Jelihovschi", "Jose Claudio Faria", "Sergio Oliveira")
    ,c("Federico Girosi", "Gary King", "Jon Bischof")
    ,c("Stefano Iacus", "Gary King", "Giuseppe Porro")
    ,c("J H Maindonald", "Randall Johnson")
    ,c("Derek Young", "Tatiana Benaglia", "Didier Chauveau" ,"Ryan Elmore", "Tom Hettmansperger", "David Hunter", "Hoben Thomas", "Fengjuan Xuan")
    ,c("Peter Filzmoser", "Heinrich Fritz Klaudius Kalcher")
    ,c("Nicole Kraemer", "Anne Laure Boulesteix")
    ,c("Yaqian Guo", "Trevor Hastie", "Robert Tibshirani")
    ,c("Adelchi Azzalini", "B D Ripley")
    ,c("Jorge Orestes Cerdeira", "Pedro Duarte Silva", "Jorge Cadima Manuel Minhoto")
    ,c("Marco Riani", "Luca Scrucca")
    ,c("Brian Ripley", "Jari Oksanen")
    ,c("Vincent Carey", "Thomas Lumley")
    ,c("Laurie Davies", "Arne Kovac")
    ,c("Christopher Jackson", "Thorsten Ottosen")
    ,c("Karsten Tabelow", "Joerg Polzehl")
    ,c("Sebastian Krey", "Uwe Ligges", "Olaf Mersmann")
    ,c("Patrick Burns", "Nick Efthymiou")
    ,c("Heinrich Fritz Klaudius Kalcher")
    ,c("Stefano Iacus", "Gary King", "Giuseppe Porro")
    ,c("Marek Walesiak", "Andrzej Dudek"))
  authors <- lapply(authors,clean2,pattern=pattern,replacement=replacement)
  if (correct){
    data(take.memory.cran)
    authors <- lapply(authors,changenames,clusters=take.memory.cran,accept=1:length(take.memory.cran))
  }
  edgelist <- c()
  for (i in seq_along(authors)){
    for (j in seq_along(authors[[i]])){
      if (length(authors[[i]])==1){
        edgelist <- rbind(edgelist,cbind(authors[[i]][j],authors[[i]][1]))
      }
      if (length(authors[[i]])>1){
        edgelist <- rbind(edgelist,cbind(authors[[i]][j],authors[[i]][-j]))
      }
    }
  }
  net <- snatm::adjacency(edgelist[,1:2],mode="multiple",directed=F)
  net <- net/2
  net
}